//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaSu.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-4EFUU78K\\SQLEXPRESS01;Initial Catalog=TRUNGTAMGIASU;Integrated" +
            " Security=True")]
        public string TRUNGTAMGIASUConnectionString {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G67KDJT;Initial Catalog=TRUNGTAMGIASU;Integrated Security=Tru" +
            "e")]
        public string TRUNGTAMGIASUConnectionString1 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-V99O7H4\\HAIDANG;Initial Catalog=TRUNGTAMGIASU;Integrated Secu" +
            "rity=True")]
        public string TRUNGTAMGIASUConnectionString2 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=TRUNGTAMGIASU;Integrated Security=True")]
        public string TRUNGTAMGIASUConnectionString3 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TRANHUYNHTANPHA;Initial Catalog=TRUNGTAMGIASU;Integrated Security=Tru" +
            "e")]
        public string TRUNGTAMGIASUConnectionString4 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-3SM2096\\SQLEXPRESS;Initial Catalog=TRUNGTAMGIASU;Integrated S" +
            "ecurity=True")]
        public string TRUNGTAMGIASUConnectionString5 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G67KDJT;Initial Catalog=TRUNGTAMGIASU;User ID=admin;Password=" +
            "admin")]
        public string TRUNGTAMGIASUConnectionString6 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G67KDJT;Initial Catalog=TRUNGTAMGIASU;User ID=giasu;Password=" +
            "giasu")]
        public string TRUNGTAMGIASUConnectionString7 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G67KDJT;Initial Catalog=TRUNGTAMGIASU;User ID=phuhuynh;Passwo" +
            "rd=phuhuynh")]
        public string TRUNGTAMGIASUConnectionString8 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-3KTA3E7I\\HAIDANG;Initial Catalog=TRUNGTAMGIASU;Integrated Secu" +
            "rity=True")]
        public string TRUNGTAMGIASUConnectionString9 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-3KTA3E7I\\HAIDANG;Initial Catalog=TRUNGTAMGIASU;User ID=admin;P" +
            "assword=admin")]
        public string TRUNGTAMGIASUConnectionString10 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-3KTA3E7I\\HAIDANG;Initial Catalog=TRUNGTAMGIASU;User ID=phuhuyn" +
            "h;Password=phuhuynh")]
        public string TRUNGTAMGIASUConnectionString11 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-3KTA3E7I\\HAIDANG;Initial Catalog=TRUNGTAMGIASU;User ID=giasu;P" +
            "assword=giasu")]
        public string TRUNGTAMGIASUConnectionString12 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TRANHUYNHTANPHA;Initial Catalog=TRUNGTAMGIASU;User ID=admin;Password=" +
            "admin")]
        public string TRUNGTAMGIASUConnectionString13 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TRANHUYNHTANPHA;Initial Catalog=TRUNGTAMGIASU;User ID=user;Password=u" +
            "ser")]
        public string TRUNGTAMGIASUConnectionString14 {
            get {
                return ((string)(this["TRUNGTAMGIASUConnectionString14"]));
            }
        }
    }
}
