<?xml version="1.0" encoding="utf-8"?><Database Name="TRUNGTAMGIASU" Class="AdminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TRANHUYNHTANPHA;Initial Catalog=TRUNGTAMGIASU;User ID=admin" SettingsObjectName="QuanLyGiaSu.Properties.Settings" SettingsPropertyName="TRUNGTAMGIASUConnectionString13" Provider="System.Data.SqlClient" />
  <Table Name="dbo.THONGTINACCOUNT" Member="THONGTINACCOUNTs">
    <Type Name="THONGTINACCOUNT">
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhanQuyen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="NganSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINPHUHUYNH_AD" Member="THONGTINPHUHUYNH_ADs">
    <Type Name="THONGTINPHUHUYNH_AD">
      <Column Name="PHID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINDANHSACHDANGKYDAY" Member="THONGTINDANHSACHDANGKYDAYs">
    <Type Name="THONGTINDANHSACHDANGKYDAY">
      <Column Name="DKID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GSID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINGIASU_AD" Member="THONGTINGIASU_ADs">
    <Type Name="THONGTINGIASU_AD">
      <Column Name="GSID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOPHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TruongDaoTao" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UuDiem" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Avartar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINLICHSUGIAODICH_AD" Member="THONGTINLICHSUGIAODICH_ADs">
    <Type Name="THONGTINLICHSUGIAODICH_AD">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINLICHSUNAPTIEN_AD" Member="THONGTINLICHSUNAPTIEN_ADs">
    <Type Name="THONGTINLICHSUNAPTIEN_AD">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINLOPMOI_AD" Member="THONGTINLOPMOI_ADs">
    <Type Name="THONGTINLOPMOI_AD">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PHID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDTLienHe" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.delete_account_accid" Method="delete_account_accid">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.update_mh" Method="update_mh">
    <Parameter Name="MHID" Parameter="mHID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENMON" Parameter="tENMON" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.delete_monhoc_lopmoi_lmid" Method="delete_monhoc_lopmoi_lmid">
    <Parameter Name="LMID" Parameter="lMID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_acc" Method="insert_acc">
    <Parameter Name="PHANQUYEN" Parameter="pHANQUYEN" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="USERNAME" Parameter="uSERNAME" Type="System.String" DbType="Char(100)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="Char(100)" />
    <Parameter Name="EMAIL" Parameter="eMAIL" Type="System.String" DbType="Char(50)" />
    <Parameter Name="NganSach" Parameter="nganSach" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_lh" Method="insert_lh">
    <Parameter Name="TENLOP" Parameter="tENLOP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_lsnt" Method="insert_lsnt">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <Parameter Name="SOTIEN" Parameter="sOTIEN" Type="System.Int32" DbType="Int" />
    <Parameter Name="TGGD" Parameter="tGGD" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_mh" Method="insert_mh">
    <Parameter Name="TENMON" Parameter="tENMON" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.update_dslm" Method="update_dslm">
    <Parameter Name="LMID" Parameter="lMID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LHID" Parameter="lHID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PHID" Parameter="pHID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="MUCLUONG" Parameter="mUCLUONG" Type="System.Int32" DbType="Int" />
    <Parameter Name="SDT" Parameter="sDT" Type="System.String" DbType="Char(50)" />
    <Parameter Name="TGDK" Parameter="tGDK" Type="System.DateTime" DbType="Date" />
    <Parameter Name="SUBUOI" Parameter="sUBUOI" Type="System.Int32" DbType="Int" />
    <Parameter Name="HINHTHUC" Parameter="hINHTHUC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TGHOC" Parameter="tGHOC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TTHOCVIEN" Parameter="tTHOCVIEN" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="YEUCAU" Parameter="yEUCAU" Type="System.String" DbType="NVarChar(300)" />
    <Parameter Name="trangthai" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="dadongtien" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.update_lh" Method="update_lh">
    <Parameter Name="LHID" Parameter="lHID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENLOP" Parameter="tENLOP" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.find_email_accid" Method="find_email_accid" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.timkiemph_tenPH" Method="timkiemph_tenPH" IsComposable="true">
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="timkiemph_tenPHResult">
      <Column Name="PHID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.find_username_accid" Method="find_username_accid" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.search_DSLM_LopHoc_AD" Method="search_DSLM_LopHoc_AD" IsComposable="true">
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="search_DSLM_LopHoc_ADResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PHID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDTLienHe" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_DSLM_MonHoc_AD" Method="search_DSLM_MonHoc_AD" IsComposable="true">
    <Parameter Name="MonHoc" Parameter="monHoc" Type="System.String" DbType="NVarChar(1)" />
    <ElementType Name="search_DSLM_MonHoc_ADResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PHID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDTLienHe" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiem_DSDKD_DKID" Method="timkiem_DSDKD_DKID" IsComposable="true">
    <Parameter Name="DKID" Parameter="dKID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiem_DSDKD_DKIDResult">
      <Column Name="DKID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GSID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemaccount_accid" Method="timkiemaccount_accid" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemaccount_accidResult">
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhanQuyen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="NganSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemaccount_username" Method="timkiemaccount_username" IsComposable="true">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="Char(30)" />
    <ElementType Name="timkiemaccount_usernameResult">
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhanQuyen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="NganSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemgs_ACCID" Method="timkiemgs_ACCID" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemgs_ACCIDResult">
      <Column Name="GSID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TruongDaoTao" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="UuDiem" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Avartar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemgs_GSID" Method="timkiemgs_GSID" IsComposable="true">
    <Parameter Name="GSID" Parameter="gSID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemgs_GSIDResult">
      <Column Name="GSID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TruongDaoTao" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="UuDiem" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Avartar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemgs_LopHoc" Method="timkiemgs_LopHoc" IsComposable="true">
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="timkiemgs_LopHocResult">
      <Column Name="GSID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOPHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TruongDaoTao" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UuDiem" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Avartar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemgs_MonHoc" Method="timkiemgs_MonHoc" IsComposable="true">
    <Parameter Name="MonHoc" Parameter="monHoc" Type="System.String" DbType="NVarChar(1)" />
    <ElementType Name="timkiemgs_MonHocResult">
      <Column Name="GSID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOPHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TruongDaoTao" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UuDiem" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Avartar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemgs_tenGS" Method="timkiemgs_tenGS" IsComposable="true">
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="timkiemgs_tenGSResult">
      <Column Name="GSID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TruongDaoTao" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="UuDiem" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Avartar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlm_LMID" Method="timkiemlm_LMID" IsComposable="true">
    <Parameter Name="LMID" Parameter="lMID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemlm_LMIDResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PHID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDTLienHe" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlsgd_ACCID" Method="timkiemlsgd_ACCID" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemlsgd_ACCIDResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlsgd_GDID" Method="timkiemlsgd_GDID" IsComposable="true">
    <Parameter Name="GDID" Parameter="gDID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemlsgd_GDIDResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlsgd_LMID" Method="timkiemlsgd_LMID" IsComposable="true">
    <Parameter Name="LMID" Parameter="lMID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemlsgd_LMIDResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlsgd_SoTien" Method="timkiemlsgd_SoTien" IsComposable="true">
    <Parameter Name="SoTien" Parameter="soTien" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemlsgd_SoTienResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlsgd_tggd" Method="timkiemlsgd_tggd" IsComposable="true">
    <Parameter Name="start_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="end_date" Type="System.DateTime" DbType="Date" />
    <ElementType Name="timkiemlsgd_tggdResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlsnt_ACCID" Method="timkiemlsnt_ACCID" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemlsnt_ACCIDResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlsnt_GDID" Method="timkiemlsnt_GDID" IsComposable="true">
    <Parameter Name="GDID" Parameter="gDID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemlsnt_GDIDResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlsnt_SoTien" Method="timkiemlsnt_SoTien" IsComposable="true">
    <Parameter Name="SoTien" Parameter="soTien" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemlsnt_SoTienResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemph_ACCID" Method="timkiemph_ACCID" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemph_ACCIDResult">
      <Column Name="PHID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemph_PHID" Method="timkiemph_PHID" IsComposable="true">
    <Parameter Name="PHID" Parameter="pHID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemph_PHIDResult">
      <Column Name="PHID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.total_annual" Method="total_annual" IsComposable="true">
    <ElementType Name="total_annualResult">
      <Column Name="month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.total_Monthly" Method="total_Monthly" IsComposable="true">
    <ElementType Name="total_MonthlyResult">
      <Column Name="month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>