#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGiaSu.src.database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TRUNGTAMGIASU")]
	public partial class UserDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public UserDataContext() : 
				base(global::QuanLyGiaSu.Properties.Settings.Default.TRUNGTAMGIASUConnectionString14, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<THONGTINGIASU_PH> THONGTINGIASU_PHs
		{
			get
			{
				return this.GetTable<THONGTINGIASU_PH>();
			}
		}
		
		public System.Data.Linq.Table<THONGTINLOPMOI_PH_G> THONGTINLOPMOI_PH_Gs
		{
			get
			{
				return this.GetTable<THONGTINLOPMOI_PH_G>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.delete_lop_giasu_gsid")]
		public int delete_lop_giasu_gsid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gsid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gsid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_mhgs")]
		public int insert_mhgs([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GSID", DbType="Int")] System.Nullable<int> gSID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mhid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gSID, mhid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.delete_monhoc_giasu_gsid")]
		public int delete_monhoc_giasu_gsid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gsid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gsid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_dsdk")]
		public int insert_dsdk([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GSID", DbType="Int")] System.Nullable<int> gSID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LMID", DbType="Int")] System.Nullable<int> lMID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TGDK", DbType="Date")] System.Nullable<System.DateTime> tGDK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gSID, lMID, tGDK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_dsml")]
		public int insert_dsml([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LHID", DbType="Int")] System.Nullable<int> lHID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PHID", DbType="Int")] System.Nullable<int> pHID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIACHI", DbType="NVarChar(4000)")] string dIACHI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MUCLUONG", DbType="Int")] System.Nullable<int> mUCLUONG, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SDT", DbType="Char(50)")] string sDT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TGDK", DbType="DateTime")] System.Nullable<System.DateTime> tGDK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUBUOI", DbType="Int")] System.Nullable<int> sUBUOI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HINHTHUC", DbType="NVarChar(50)")] string hINHTHUC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TGHOC", DbType="NVarChar(50)")] string tGHOC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TTHOCVIEN", DbType="NVarChar(50)")] string tTHOCVIEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YEUCAU", DbType="NVarChar(300)")] string yEUCAU)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lHID, pHID, dIACHI, mUCLUONG, sDT, tGDK, sUBUOI, hINHTHUC, tGHOC, tTHOCVIEN, yEUCAU);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_lhgs")]
		public int insert_lhgs([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GSID", DbType="Int")] System.Nullable<int> gSID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lhid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gSID, lhid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.danhsachlop_damo", IsComposable=true)]
		public IQueryable<danhsachlop_damoResult> danhsachlop_damo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PHID", DbType="Int")] System.Nullable<int> pHID)
		{
			return this.CreateMethodCallQuery<danhsachlop_damoResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pHID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiemlm_ph_gs_LMID", IsComposable=true)]
		public IQueryable<timkiemlm_ph_gs_LMIDResult> timkiemlm_ph_gs_LMID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LMID", DbType="Int")] System.Nullable<int> lMID)
		{
			return this.CreateMethodCallQuery<timkiemlm_ph_gs_LMIDResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lMID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.search_DSLM_LopHoc_PH_GS", IsComposable=true)]
		public IQueryable<search_DSLM_LopHoc_PH_GSResult> search_DSLM_LopHoc_PH_GS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenLop", DbType="NVarChar(50)")] string tenLop)
		{
			return this.CreateMethodCallQuery<search_DSLM_LopHoc_PH_GSResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenLop);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.search_DSLM_MonHoc_PH_GS", IsComposable=true)]
		public IQueryable<search_DSLM_MonHoc_PH_GSResult> search_DSLM_MonHoc_PH_GS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonHoc", DbType="NVarChar(1)")] string monHoc)
		{
			return this.CreateMethodCallQuery<search_DSLM_MonHoc_PH_GSResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), monHoc);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_danhsachlopmoi_dadangkyday", IsComposable=true)]
		public IQueryable<select_danhsachlopmoi_dadangkydayResult> select_danhsachlopmoi_dadangkyday([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GSID", DbType="Int")] System.Nullable<int> gSID)
		{
			return this.CreateMethodCallQuery<select_danhsachlopmoi_dadangkydayResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gSID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_lichsugiaodich", IsComposable=true)]
		public IQueryable<select_lichsugiaodichResult> select_lichsugiaodich([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACCID", DbType="Int")] System.Nullable<int> aCCID)
		{
			return this.CreateMethodCallQuery<select_lichsugiaodichResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCCID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_lichsunaptien", IsComposable=true)]
		public IQueryable<select_lichsunaptienResult> select_lichsunaptien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACCID", DbType="Int")] System.Nullable<int> aCCID)
		{
			return this.CreateMethodCallQuery<select_lichsunaptienResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCCID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_ngansach", IsComposable=true)]
		public System.Nullable<int> select_ngansach([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACCID", DbType="Int")] System.Nullable<int> aCCID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCCID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.thongtingiasu_private", IsComposable=true)]
		public IQueryable<thongtingiasu_privateResult> thongtingiasu_private([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACCID", DbType="Int")] System.Nullable<int> aCCID)
		{
			return this.CreateMethodCallQuery<thongtingiasu_privateResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCCID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.thongtinphuhuynh_private", IsComposable=true)]
		public IQueryable<thongtinphuhuynh_privateResult> thongtinphuhuynh_private([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACCID", DbType="Int")] System.Nullable<int> aCCID)
		{
			return this.CreateMethodCallQuery<thongtinphuhuynh_privateResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCCID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_DSDK_LMID", IsComposable=true)]
		public IQueryable<timkiem_DSDK_LMIDResult> timkiem_DSDK_LMID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GSID", DbType="Int")] System.Nullable<int> gSID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LMID", DbType="Int")] System.Nullable<int> lMID)
		{
			return this.CreateMethodCallQuery<timkiem_DSDK_LMIDResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gSID, lMID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_DSDK_LopHoc", IsComposable=true)]
		public IQueryable<timkiem_DSDK_LopHocResult> timkiem_DSDK_LopHoc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GSID", DbType="Int")] System.Nullable<int> gSID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenLop", DbType="NVarChar(20)")] string tenLop)
		{
			return this.CreateMethodCallQuery<timkiem_DSDK_LopHocResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gSID, tenLop);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_DSDK_MonHoc", IsComposable=true)]
		public IQueryable<timkiem_DSDK_MonHocResult> timkiem_DSDK_MonHoc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GSID", DbType="Int")] System.Nullable<int> gSID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonHoc", DbType="NVarChar(20)")] string monHoc)
		{
			return this.CreateMethodCallQuery<timkiem_DSDK_MonHocResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gSID, monHoc);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_DSLDM_LMID", IsComposable=true)]
		public IQueryable<timkiem_DSLDM_LMIDResult> timkiem_DSLDM_LMID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PHID", DbType="Int")] System.Nullable<int> pHID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LMID", DbType="Int")] System.Nullable<int> lMID)
		{
			return this.CreateMethodCallQuery<timkiem_DSLDM_LMIDResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pHID, lMID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_DSLDM_LopHoc", IsComposable=true)]
		public IQueryable<timkiem_DSLDM_LopHocResult> timkiem_DSLDM_LopHoc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PHID", DbType="Int")] System.Nullable<int> pHID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenLop", DbType="NVarChar(50)")] string tenLop)
		{
			return this.CreateMethodCallQuery<timkiem_DSLDM_LopHocResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pHID, tenLop);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_DSLDM_MonHoc", IsComposable=true)]
		public IQueryable<timkiem_DSLDM_MonHocResult> timkiem_DSLDM_MonHoc([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PHID", DbType="Int")] System.Nullable<int> pHID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonHoc", DbType="NVarChar(1)")] string monHoc)
		{
			return this.CreateMethodCallQuery<timkiem_DSLDM_MonHocResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pHID, monHoc);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINGIASU_PH")]
	public partial class THONGTINGIASU_PH
	{
		
		private System.Nullable<int> _GSID;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _MONHOC_LIST;
		
		private string _LOPHOC_LIST;
		
		private string _QueQuan;
		
		private string _TruongDaoTao;
		
		private string _TrinhDo;
		
		private string _UuDiem;
		
		private string _DiaChi;
		
		private System.Data.Linq.Binary _Avartar;
		
		public THONGTINGIASU_PH()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSID", DbType="Int")]
		public System.Nullable<int> GSID
		{
			get
			{
				return this._GSID;
			}
			set
			{
				if ((this._GSID != value))
				{
					this._GSID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(20)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOPHOC_LIST", DbType="NVarChar(MAX)")]
		public string LOPHOC_LIST
		{
			get
			{
				return this._LOPHOC_LIST;
			}
			set
			{
				if ((this._LOPHOC_LIST != value))
				{
					this._LOPHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(500)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this._QueQuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongDaoTao", DbType="NVarChar(500)")]
		public string TruongDaoTao
		{
			get
			{
				return this._TruongDaoTao;
			}
			set
			{
				if ((this._TruongDaoTao != value))
				{
					this._TruongDaoTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDo", DbType="NVarChar(4000)")]
		public string TrinhDo
		{
			get
			{
				return this._TrinhDo;
			}
			set
			{
				if ((this._TrinhDo != value))
				{
					this._TrinhDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UuDiem", DbType="NVarChar(4000)")]
		public string UuDiem
		{
			get
			{
				return this._UuDiem;
			}
			set
			{
				if ((this._UuDiem != value))
				{
					this._UuDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(4000)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avartar", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Avartar
		{
			get
			{
				return this._Avartar;
			}
			set
			{
				if ((this._Avartar != value))
				{
					this._Avartar = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINLOPMOI_PH_GS")]
	public partial class THONGTINLOPMOI_PH_G
	{
		
		private System.Nullable<int> _LMID;
		
		private string _MONHOC_LIST;
		
		private string _TenLop;
		
		private string _DiaChi;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private string _ThoiGianHoc;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public THONGTINLOPMOI_PH_G()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class danhsachlop_damoResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _MONHOC_LIST;
		
		private string _TenLop;
		
		private string _DiaChi;
		
		private string _SDTLienHe;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private string _ThoiGianHoc;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public danhsachlop_damoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTLienHe", DbType="Char(20)")]
		public string SDTLienHe
		{
			get
			{
				return this._SDTLienHe;
			}
			set
			{
				if ((this._SDTLienHe != value))
				{
					this._SDTLienHe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class timkiemlm_ph_gs_LMIDResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _MONHOC_LIST;
		
		private string _TenLop;
		
		private string _DiaChi;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private string _ThoiGianHoc;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public timkiemlm_ph_gs_LMIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class search_DSLM_LopHoc_PH_GSResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _MONHOC_LIST;
		
		private string _TenLop;
		
		private string _DiaChi;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private string _ThoiGianHoc;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public search_DSLM_LopHoc_PH_GSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class search_DSLM_MonHoc_PH_GSResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _MONHOC_LIST;
		
		private string _TenLop;
		
		private string _DiaChi;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private string _ThoiGianHoc;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public search_DSLM_MonHoc_PH_GSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class select_danhsachlopmoi_dadangkydayResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _HoTen;
		
		private string _TenLop;
		
		private string _TenMon;
		
		private string _DiaChi;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThoiGianHoc;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public select_danhsachlopmoi_dadangkydayResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(MAX)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this._TenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class select_lichsugiaodichResult
	{
		
		private int _GDID;
		
		private int _LMID;
		
		private int _SoTien;
		
		private System.Nullable<System.DateTime> _ThoiGianGiaoDich;
		
		public select_lichsugiaodichResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GDID", DbType="Int NOT NULL")]
		public int GDID
		{
			get
			{
				return this._GDID;
			}
			set
			{
				if ((this._GDID != value))
				{
					this._GDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int NOT NULL")]
		public int LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Int NOT NULL")]
		public int SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this._SoTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianGiaoDich", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianGiaoDich
		{
			get
			{
				return this._ThoiGianGiaoDich;
			}
			set
			{
				if ((this._ThoiGianGiaoDich != value))
				{
					this._ThoiGianGiaoDich = value;
				}
			}
		}
	}
	
	public partial class select_lichsunaptienResult
	{
		
		private int _GDID;
		
		private int _ACCID;
		
		private int _SoTien;
		
		private System.Nullable<System.DateTime> _THOIGIANGIAODICH;
		
		public select_lichsunaptienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GDID", DbType="Int NOT NULL")]
		public int GDID
		{
			get
			{
				return this._GDID;
			}
			set
			{
				if ((this._GDID != value))
				{
					this._GDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCID", DbType="Int NOT NULL")]
		public int ACCID
		{
			get
			{
				return this._ACCID;
			}
			set
			{
				if ((this._ACCID != value))
				{
					this._ACCID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTien", DbType="Int NOT NULL")]
		public int SoTien
		{
			get
			{
				return this._SoTien;
			}
			set
			{
				if ((this._SoTien != value))
				{
					this._SoTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANGIAODICH", DbType="DateTime")]
		public System.Nullable<System.DateTime> THOIGIANGIAODICH
		{
			get
			{
				return this._THOIGIANGIAODICH;
			}
			set
			{
				if ((this._THOIGIANGIAODICH != value))
				{
					this._THOIGIANGIAODICH = value;
				}
			}
		}
	}
	
	public partial class thongtingiasu_privateResult
	{
		
		private System.Nullable<int> _ACCID;
		
		private System.Nullable<int> _GSID;
		
		private string _CMND;
		
		private System.Data.Linq.Binary _Avartar;
		
		private string _DiaChi;
		
		private string _GioiTinh;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _QueQuan;
		
		private string _SDT;
		
		private string _TrinhDo;
		
		private string _TruongDaoTao;
		
		private string _UuDiem;
		
		private string _Email;
		
		private int _NganSach;
		
		private string _Password;
		
		private string _PhanQuyen;
		
		private string _Username;
		
		private string _MONHOC_LIST;
		
		private string _LOPHOC_LIST;
		
		public thongtingiasu_privateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCID", DbType="Int")]
		public System.Nullable<int> ACCID
		{
			get
			{
				return this._ACCID;
			}
			set
			{
				if ((this._ACCID != value))
				{
					this._ACCID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GSID", DbType="Int")]
		public System.Nullable<int> GSID
		{
			get
			{
				return this._GSID;
			}
			set
			{
				if ((this._GSID != value))
				{
					this._GSID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(20)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this._CMND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avartar", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Avartar
		{
			get
			{
				return this._Avartar;
			}
			set
			{
				if ((this._Avartar != value))
				{
					this._Avartar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(4000)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(20)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(500)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this._QueQuan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrinhDo", DbType="NVarChar(4000)")]
		public string TrinhDo
		{
			get
			{
				return this._TrinhDo;
			}
			set
			{
				if ((this._TrinhDo != value))
				{
					this._TrinhDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongDaoTao", DbType="NVarChar(500)")]
		public string TruongDaoTao
		{
			get
			{
				return this._TruongDaoTao;
			}
			set
			{
				if ((this._TruongDaoTao != value))
				{
					this._TruongDaoTao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UuDiem", DbType="NVarChar(4000)")]
		public string UuDiem
		{
			get
			{
				return this._UuDiem;
			}
			set
			{
				if ((this._UuDiem != value))
				{
					this._UuDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganSach", DbType="Int NOT NULL")]
		public int NganSach
		{
			get
			{
				return this._NganSach;
			}
			set
			{
				if ((this._NganSach != value))
				{
					this._NganSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanQuyen", DbType="NVarChar(30)")]
		public string PhanQuyen
		{
			get
			{
				return this._PhanQuyen;
			}
			set
			{
				if ((this._PhanQuyen != value))
				{
					this._PhanQuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOPHOC_LIST", DbType="NVarChar(MAX)")]
		public string LOPHOC_LIST
		{
			get
			{
				return this._LOPHOC_LIST;
			}
			set
			{
				if ((this._LOPHOC_LIST != value))
				{
					this._LOPHOC_LIST = value;
				}
			}
		}
	}
	
	public partial class thongtinphuhuynh_privateResult
	{
		
		private int _ACCID;
		
		private string _CMND;
		
		private string _DiaChi;
		
		private string _GioiTinh;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _NgheNghiep;
		
		private int _PHID;
		
		private string _SDT;
		
		private string _Email;
		
		private int _NganSach;
		
		private string _Password;
		
		private string _PhanQuyen;
		
		private string _Username;
		
		public thongtinphuhuynh_privateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACCID", DbType="Int NOT NULL")]
		public int ACCID
		{
			get
			{
				return this._ACCID;
			}
			set
			{
				if ((this._ACCID != value))
				{
					this._ACCID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this._CMND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNghiep", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string NgheNghiep
		{
			get
			{
				return this._NgheNghiep;
			}
			set
			{
				if ((this._NgheNghiep != value))
				{
					this._NgheNghiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHID", DbType="Int NOT NULL")]
		public int PHID
		{
			get
			{
				return this._PHID;
			}
			set
			{
				if ((this._PHID != value))
				{
					this._PHID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this._SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganSach", DbType="Int NOT NULL")]
		public int NganSach
		{
			get
			{
				return this._NganSach;
			}
			set
			{
				if ((this._NganSach != value))
				{
					this._NganSach = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanQuyen", DbType="NVarChar(30)")]
		public string PhanQuyen
		{
			get
			{
				return this._PhanQuyen;
			}
			set
			{
				if ((this._PhanQuyen != value))
				{
					this._PhanQuyen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
	}
	
	public partial class timkiem_DSDK_LMIDResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _HoTen;
		
		private string _TenLop;
		
		private string _TenMon;
		
		private string _DiaChi;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThoiGianHoc;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public timkiem_DSDK_LMIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(MAX)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this._TenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class timkiem_DSDK_LopHocResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _HoTen;
		
		private string _TenLop;
		
		private string _TenMon;
		
		private string _DiaChi;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThoiGianHoc;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public timkiem_DSDK_LopHocResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(MAX)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this._TenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class timkiem_DSDK_MonHocResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _HoTen;
		
		private string _TenLop;
		
		private string _TenMon;
		
		private string _DiaChi;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThoiGianHoc;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public timkiem_DSDK_MonHocResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(MAX)")]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this._TenMon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class timkiem_DSLDM_LMIDResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _MONHOC_LIST;
		
		private string _TenLop;
		
		private string _DiaChi;
		
		private string _SDTLienHe;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private string _ThoiGianHoc;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public timkiem_DSLDM_LMIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTLienHe", DbType="Char(20)")]
		public string SDTLienHe
		{
			get
			{
				return this._SDTLienHe;
			}
			set
			{
				if ((this._SDTLienHe != value))
				{
					this._SDTLienHe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class timkiem_DSLDM_LopHocResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _MONHOC_LIST;
		
		private string _TenLop;
		
		private string _DiaChi;
		
		private string _SDTLienHe;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private string _ThoiGianHoc;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public timkiem_DSLDM_LopHocResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTLienHe", DbType="Char(20)")]
		public string SDTLienHe
		{
			get
			{
				return this._SDTLienHe;
			}
			set
			{
				if ((this._SDTLienHe != value))
				{
					this._SDTLienHe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	public partial class timkiem_DSLDM_MonHocResult
	{
		
		private System.Nullable<int> _LMID;
		
		private string _MONHOC_LIST;
		
		private string _TenLop;
		
		private string _DiaChi;
		
		private string _SDTLienHe;
		
		private System.Nullable<int> _MucLuong;
		
		private System.Nullable<System.DateTime> _ThoiGianDangKy;
		
		private string _ThoiGianHoc;
		
		private System.Nullable<int> _SoBuoi;
		
		private string _HinhThucDay;
		
		private string _ThongTinHocVien;
		
		private string _YeuCauGiaSu;
		
		private string _TrangThai;
		
		public timkiem_DSLDM_MonHocResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LMID", DbType="Int")]
		public System.Nullable<int> LMID
		{
			get
			{
				return this._LMID;
			}
			set
			{
				if ((this._LMID != value))
				{
					this._LMID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MONHOC_LIST", DbType="NVarChar(MAX)")]
		public string MONHOC_LIST
		{
			get
			{
				return this._MONHOC_LIST;
			}
			set
			{
				if ((this._MONHOC_LIST != value))
				{
					this._MONHOC_LIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLop", DbType="NVarChar(50)")]
		public string TenLop
		{
			get
			{
				return this._TenLop;
			}
			set
			{
				if ((this._TenLop != value))
				{
					this._TenLop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTLienHe", DbType="Char(20)")]
		public string SDTLienHe
		{
			get
			{
				return this._SDTLienHe;
			}
			set
			{
				if ((this._SDTLienHe != value))
				{
					this._SDTLienHe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Int")]
		public System.Nullable<int> MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this._MucLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianDangKy
		{
			get
			{
				return this._ThoiGianDangKy;
			}
			set
			{
				if ((this._ThoiGianDangKy != value))
				{
					this._ThoiGianDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHoc", DbType="NVarChar(50)")]
		public string ThoiGianHoc
		{
			get
			{
				return this._ThoiGianHoc;
			}
			set
			{
				if ((this._ThoiGianHoc != value))
				{
					this._ThoiGianHoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoi", DbType="Int")]
		public System.Nullable<int> SoBuoi
		{
			get
			{
				return this._SoBuoi;
			}
			set
			{
				if ((this._SoBuoi != value))
				{
					this._SoBuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucDay", DbType="NVarChar(50)")]
		public string HinhThucDay
		{
			get
			{
				return this._HinhThucDay;
			}
			set
			{
				if ((this._HinhThucDay != value))
				{
					this._HinhThucDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHocVien", DbType="NVarChar(500)")]
		public string ThongTinHocVien
		{
			get
			{
				return this._ThongTinHocVien;
			}
			set
			{
				if ((this._ThongTinHocVien != value))
				{
					this._ThongTinHocVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauGiaSu", DbType="NVarChar(500)")]
		public string YeuCauGiaSu
		{
			get
			{
				return this._YeuCauGiaSu;
			}
			set
			{
				if ((this._YeuCauGiaSu != value))
				{
					this._YeuCauGiaSu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
