<?xml version="1.0" encoding="utf-8"?><Database Name="TRUNGTAMGIASU" Class="UserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TRANHUYNHTANPHA;Initial Catalog=TRUNGTAMGIASU;User ID=user" SettingsObjectName="QuanLyGiaSu.Properties.Settings" SettingsPropertyName="TRUNGTAMGIASUConnectionString14" Provider="System.Data.SqlClient" />
  <Table Name="dbo.THONGTINGIASU_PH" Member="THONGTINGIASU_PHs">
    <Type Name="THONGTINGIASU_PH">
      <Column Name="GSID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOPHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TruongDaoTao" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="UuDiem" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Avartar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINLOPMOI_PH_GS" Member="THONGTINLOPMOI_PH_Gs">
    <Type Name="THONGTINLOPMOI_PH_G">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.delete_lop_giasu_gsid" Method="delete_lop_giasu_gsid">
    <Parameter Name="gsid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_mhgs" Method="insert_mhgs">
    <Parameter Name="GSID" Parameter="gSID" Type="System.Int32" DbType="Int" />
    <Parameter Name="mhid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.delete_monhoc_giasu_gsid" Method="delete_monhoc_giasu_gsid">
    <Parameter Name="gsid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_dsdk" Method="insert_dsdk">
    <Parameter Name="GSID" Parameter="gSID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LMID" Parameter="lMID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TGDK" Parameter="tGDK" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_dsml" Method="insert_dsml">
    <Parameter Name="LHID" Parameter="lHID" Type="System.Int32" DbType="Int" />
    <Parameter Name="PHID" Parameter="pHID" Type="System.Int32" DbType="Int" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="MUCLUONG" Parameter="mUCLUONG" Type="System.Int32" DbType="Int" />
    <Parameter Name="SDT" Parameter="sDT" Type="System.String" DbType="Char(50)" />
    <Parameter Name="TGDK" Parameter="tGDK" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SUBUOI" Parameter="sUBUOI" Type="System.Int32" DbType="Int" />
    <Parameter Name="HINHTHUC" Parameter="hINHTHUC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TGHOC" Parameter="tGHOC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="TTHOCVIEN" Parameter="tTHOCVIEN" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="YEUCAU" Parameter="yEUCAU" Type="System.String" DbType="NVarChar(300)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insert_lhgs" Method="insert_lhgs">
    <Parameter Name="GSID" Parameter="gSID" Type="System.Int32" DbType="Int" />
    <Parameter Name="lhid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.danhsachlop_damo" Method="danhsachlop_damo" IsComposable="true">
    <Parameter Name="PHID" Parameter="pHID" Type="System.Int32" DbType="Int" />
    <ElementType Name="danhsachlop_damoResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDTLienHe" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiemlm_ph_gs_LMID" Method="timkiemlm_ph_gs_LMID" IsComposable="true">
    <Parameter Name="LMID" Parameter="lMID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiemlm_ph_gs_LMIDResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_DSLM_LopHoc_PH_GS" Method="search_DSLM_LopHoc_PH_GS" IsComposable="true">
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="search_DSLM_LopHoc_PH_GSResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_DSLM_MonHoc_PH_GS" Method="search_DSLM_MonHoc_PH_GS" IsComposable="true">
    <Parameter Name="MonHoc" Parameter="monHoc" Type="System.String" DbType="NVarChar(1)" />
    <ElementType Name="search_DSLM_MonHoc_PH_GSResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_danhsachlopmoi_dadangkyday" Method="select_danhsachlopmoi_dadangkyday" IsComposable="true">
    <Parameter Name="GSID" Parameter="gSID" Type="System.Int32" DbType="Int" />
    <ElementType Name="select_danhsachlopmoi_dadangkydayResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_lichsugiaodich" Method="select_lichsugiaodich" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="select_lichsugiaodichResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LMID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_lichsunaptien" Method="select_lichsunaptien" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="select_lichsunaptienResult">
      <Column Name="GDID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="THOIGIANGIAODICH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.select_ngansach" Method="select_ngansach" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.thongtingiasu_private" Method="thongtingiasu_private" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="thongtingiasu_privateResult">
      <Column Name="ACCID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GSID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="Avartar" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="TrinhDo" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="TruongDaoTao" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="UuDiem" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="NganSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhanQuyen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOPHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.thongtinphuhuynh_private" Method="thongtinphuhuynh_private" IsComposable="true">
    <Parameter Name="ACCID" Parameter="aCCID" Type="System.Int32" DbType="Int" />
    <ElementType Name="thongtinphuhuynh_privateResult">
      <Column Name="ACCID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="PHID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="NganSach" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
      <Column Name="PhanQuyen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="Char(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiem_DSDK_LMID" Method="timkiem_DSDK_LMID" IsComposable="true">
    <Parameter Name="GSID" Parameter="gSID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LMID" Parameter="lMID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiem_DSDK_LMIDResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiem_DSDK_LopHoc" Method="timkiem_DSDK_LopHoc" IsComposable="true">
    <Parameter Name="GSID" Parameter="gSID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="timkiem_DSDK_LopHocResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiem_DSDK_MonHoc" Method="timkiem_DSDK_MonHoc" IsComposable="true">
    <Parameter Name="GSID" Parameter="gSID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MonHoc" Parameter="monHoc" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="timkiem_DSDK_MonHocResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiem_DSLDM_LMID" Method="timkiem_DSLDM_LMID" IsComposable="true">
    <Parameter Name="PHID" Parameter="pHID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LMID" Parameter="lMID" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiem_DSLDM_LMIDResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDTLienHe" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiem_DSLDM_LopHoc" Method="timkiem_DSLDM_LopHoc" IsComposable="true">
    <Parameter Name="PHID" Parameter="pHID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="timkiem_DSLDM_LopHocResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDTLienHe" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiem_DSLDM_MonHoc" Method="timkiem_DSLDM_MonHoc" IsComposable="true">
    <Parameter Name="PHID" Parameter="pHID" Type="System.Int32" DbType="Int" />
    <Parameter Name="MonHoc" Parameter="monHoc" Type="System.String" DbType="NVarChar(1)" />
    <ElementType Name="timkiem_DSLDM_MonHocResult">
      <Column Name="LMID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MONHOC_LIST" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SDTLienHe" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianDangKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianHoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoBuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhThucDay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinHocVien" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="YeuCauGiaSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>